// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Activity struct {
	// Message for activity. Supports handlebars syntax.
	Message string                 `json:"message"`
	Payload map[string]interface{} `json:"payload,omitempty"`
	// Title for activity. Supports handlebars syntax.
	Title string `json:"title"`
	Type  string `json:"type"`
}
