// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type EntityViewDisabledViewTypeEnum string

const (
	EntityViewDisabledViewTypeEnumDisabled EntityViewDisabledViewTypeEnum = "disabled"
)

func (e EntityViewDisabledViewTypeEnum) ToPointer() *EntityViewDisabledViewTypeEnum {
	return &e
}

func (e *EntityViewDisabledViewTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "disabled":
		*e = EntityViewDisabledViewTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EntityViewDisabledViewTypeEnum: %v", v)
	}
}

type EntityViewDisabled struct {
	ViewType *EntityViewDisabledViewTypeEnum `json:"view_type,omitempty"`
}
