// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"time"
)

// EntityItem - Success
type EntityItem struct {
	CreatedAt time.Time `json:"_created_at"`
	ID        string    `json:"_id"`
	// Organization Id the entity belongs to
	Org string `json:"_org"`
	// URL-friendly identifier for the entity schema
	Schema string   `json:"_schema"`
	Tags   []string `json:"_tags,omitempty"`
	// Title of entity
	Title     string    `json:"_title"`
	UpdatedAt time.Time `json:"_updated_at"`

	Entity interface{} `json:"-"`
}
type _EntityItem EntityItem

func (c *EntityItem) UnmarshalJSON(bs []byte) error {
	data := _EntityItem{}

	if err := json.Unmarshal(bs, &data); err != nil {
		return err
	}
	*c = EntityItem(data)

	additionalFields := make(map[string]interface{})

	if err := json.Unmarshal(bs, &additionalFields); err != nil {
		return err
	}
	delete(additionalFields, "_created_at")
	delete(additionalFields, "_id")
	delete(additionalFields, "_org")
	delete(additionalFields, "_schema")
	delete(additionalFields, "_tags")
	delete(additionalFields, "_title")
	delete(additionalFields, "_updated_at")

	c.Entity = additionalFields

	return nil
}

func (c EntityItem) MarshalJSON() ([]byte, error) {
	out := map[string]interface{}{}
	bs, err := json.Marshal(_EntityItem(c))
	if err != nil {
		return nil, err
	}

	if err := json.Unmarshal([]byte(bs), &out); err != nil {
		return nil, err
	}

	bs, err = json.Marshal(c.Entity)
	if err != nil {
		return nil, err
	}

	if err := json.Unmarshal([]byte(bs), &out); err != nil {
		return nil, err
	}

	return json.Marshal(out)
}
