// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Aggregations struct {
}

type EntitySearchResults struct {
	Aggregations *Aggregations `json:"aggregations,omitempty"`
	Hits         *float64      `json:"hits,omitempty"`
	Results      []EntityItem  `json:"results,omitempty"`
}

func (o *EntitySearchResults) GetAggregations() *Aggregations {
	if o == nil {
		return nil
	}
	return o.Aggregations
}

func (o *EntitySearchResults) GetHits() *float64 {
	if o == nil {
		return nil
	}
	return o.Hits
}

func (o *EntitySearchResults) GetResults() []EntityItem {
	if o == nil {
		return nil
	}
	return o.Results
}
