// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type TableMenuOptions struct {
	Icon  *string `json:"icon,omitempty"`
	Label *string `json:"label,omitempty"`
}

func (o *TableMenuOptions) GetIcon() *string {
	if o == nil {
		return nil
	}
	return o.Icon
}

func (o *TableMenuOptions) GetLabel() *string {
	if o == nil {
		return nil
	}
	return o.Label
}

type ViewType string

const (
	ViewTypeDefault ViewType = "default"
)

func (e ViewType) ToPointer() *ViewType {
	return &e
}

func (e *ViewType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "default":
		*e = ViewType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ViewType: %v", v)
	}
}

type EntityDefaultCreate struct {
	SearchParams     map[string]string `json:"search_params,omitempty"`
	TableMenuOptions *TableMenuOptions `json:"table_menu_options,omitempty"`
	ViewType         *ViewType         `json:"view_type,omitempty"`
}

func (o *EntityDefaultCreate) GetSearchParams() map[string]string {
	if o == nil {
		return nil
	}
	return o.SearchParams
}

func (o *EntityDefaultCreate) GetTableMenuOptions() *TableMenuOptions {
	if o == nil {
		return nil
	}
	return o.TableMenuOptions
}

func (o *EntityDefaultCreate) GetViewType() *ViewType {
	if o == nil {
		return nil
	}
	return o.ViewType
}
