// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EntitySearchResults - Success
type EntitySearchResults struct {
	Hits    *float64     `json:"hits,omitempty"`
	Results []EntityItem `json:"results,omitempty"`
}
