// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EntityCapabilityUIHooksRequiredPermission - Require a permission to display UI hook
type EntityCapabilityUIHooksRequiredPermission struct {
	Action   string  `json:"action"`
	Resource *string `json:"resource,omitempty"`
}

type EntityCapabilityUIHooks struct {
	// the component to be dynamically loaded
	Component *string `json:"component,omitempty"`
	// Whether capability should be disabled
	Disabled *bool `json:"disabled,omitempty"`
	// Sets the group expand/collapse default state
	GroupExpanded *bool `json:"group_expanded,omitempty"`
	// Specific to Activity pilot
	Header *bool `json:"header,omitempty"`
	// name of the hook to use
	Hook string `json:"hook"`
	// Preview icon name(As in Base elements) for the capability
	Icon *string `json:"icon,omitempty"`
	// package to be imported
	Import *string `json:"import,omitempty"`
	// render order (ascending)
	Order           *int64  `json:"order,omitempty"`
	RenderCondition *string `json:"render_condition,omitempty"`
	// Require a permission to display UI hook
	RequiredPermission *EntityCapabilityUIHooksRequiredPermission `json:"requiredPermission,omitempty"`
	// route for specified capability
	Route *string `json:"route,omitempty"`
	Title *string `json:"title,omitempty"`
}

// EntityCapability - Capabilities the Entity has. Turn features on/off for entities.
type EntityCapability struct {
	Purpose    []string    `json:"_purpose,omitempty"`
	Attributes []Attribute `json:"attributes,omitempty"`
	// This capability should only be active when the feature flag is enabled
	FeatureFlag *string `json:"feature_flag,omitempty"`
	// Only show capability for legacy tenants (ivy)
	Legacy *bool `json:"legacy,omitempty"`
	// Unique name for the capability
	Name string `json:"name"`
	// This capability should only be active when the setting is enabled
	SettingFlag *string `json:"setting_flag,omitempty"`
	// Human readable title of the capability
	Title   *string                   `json:"title,omitempty"`
	UIHooks []EntityCapabilityUIHooks `json:"ui_hooks,omitempty"`
}
