// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type EntityViewDisabledViewTypeEnum string

const (
	EntityViewDisabledViewTypeEnumDisabled EntityViewDisabledViewTypeEnum = "disabled"
)

func (e *EntityViewDisabledViewTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "disabled":
		*e = EntityViewDisabledViewTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for EntityViewDisabledViewTypeEnum: %s", s)
	}
}

type EntityViewDisabled struct {
	ViewType *EntityViewDisabledViewTypeEnum `json:"view_type,omitempty"`
}
