// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetRelationsRespWithPagination - Success
type GetRelationsRespWithPagination struct {
	Hits      *float64      `json:"hits,omitempty"`
	Relations []interface{} `json:"relations,omitempty"`
}
