// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type RedirectEntityViewViewType string

const (
	RedirectEntityViewViewTypeRedirect RedirectEntityViewViewType = "redirect"
)

func (e RedirectEntityViewViewType) ToPointer() *RedirectEntityViewViewType {
	return &e
}

func (e *RedirectEntityViewViewType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "redirect":
		*e = RedirectEntityViewViewType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RedirectEntityViewViewType: %v", v)
	}
}

type RedirectEntityView struct {
	Route    *string                     `json:"route,omitempty"`
	ViewType *RedirectEntityViewViewType `json:"view_type,omitempty"`
}

func (o *RedirectEntityView) GetRoute() *string {
	if o == nil {
		return nil
	}
	return o.Route
}

func (o *RedirectEntityView) GetViewType() *RedirectEntityViewViewType {
	if o == nil {
		return nil
	}
	return o.ViewType
}
