// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type RedirectEntityViewViewTypeEnum string

const (
	RedirectEntityViewViewTypeEnumRedirect RedirectEntityViewViewTypeEnum = "redirect"
)

func (e *RedirectEntityViewViewTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "redirect":
		*e = RedirectEntityViewViewTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for RedirectEntityViewViewTypeEnum: %s", s)
	}
}

type RedirectEntityView struct {
	Route    *string                         `json:"route,omitempty"`
	ViewType *RedirectEntityViewViewTypeEnum `json:"view_type,omitempty"`
}
