// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type RedirectEntityViewViewTypeEnum string

const (
	RedirectEntityViewViewTypeEnumRedirect RedirectEntityViewViewTypeEnum = "redirect"
)

func (e RedirectEntityViewViewTypeEnum) ToPointer() *RedirectEntityViewViewTypeEnum {
	return &e
}

func (e *RedirectEntityViewViewTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "redirect":
		*e = RedirectEntityViewViewTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RedirectEntityViewViewTypeEnum: %v", v)
	}
}

type RedirectEntityView struct {
	Route    *string                         `json:"route,omitempty"`
	ViewType *RedirectEntityViewViewTypeEnum `json:"view_type,omitempty"`
}
