// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"time"
)

// RelationAttributeActionsActionType - The action type. Currently supported actions:
//
// | action | description |
// |--------|-------------|
// | add_existing | Enables the user to pick an existing entity to link as relation |
// | create_new | Enables the user to create a new entity using the first/main `allowed_schemas` schema
// | create_from_existing | Enables the user to pick an existing entity to clone from, while creating a blank new entity to link as relation |
type RelationAttributeActionsActionType string

const (
	RelationAttributeActionsActionTypeAddExisting        RelationAttributeActionsActionType = "add_existing"
	RelationAttributeActionsActionTypeCreateNew          RelationAttributeActionsActionType = "create_new"
	RelationAttributeActionsActionTypeCreateFromExisting RelationAttributeActionsActionType = "create_from_existing"
)

func (e RelationAttributeActionsActionType) ToPointer() *RelationAttributeActionsActionType {
	return &e
}

func (e *RelationAttributeActionsActionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "add_existing":
		fallthrough
	case "create_new":
		fallthrough
	case "create_from_existing":
		*e = RelationAttributeActionsActionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RelationAttributeActionsActionType: %v", v)
	}
}

type RelationAttributeActionsNewEntityItem struct {
	CreatedAt time.Time `json:"_created_at"`
	ID        string    `json:"_id"`
	// Organization Id the entity belongs to
	Org string `json:"_org"`
	// URL-friendly identifier for the entity schema
	Schema string   `json:"_schema"`
	Tags   []string `json:"_tags,omitempty"`
	// Title of entity
	Title     string    `json:"_title"`
	UpdatedAt time.Time `json:"_updated_at"`

	Entity interface{} `json:"-"`
}
type _RelationAttributeActionsNewEntityItem RelationAttributeActionsNewEntityItem

func (c *RelationAttributeActionsNewEntityItem) UnmarshalJSON(bs []byte) error {
	data := _RelationAttributeActionsNewEntityItem{}

	if err := json.Unmarshal(bs, &data); err != nil {
		return err
	}
	*c = RelationAttributeActionsNewEntityItem(data)

	additionalFields := make(map[string]interface{})

	if err := json.Unmarshal(bs, &additionalFields); err != nil {
		return err
	}
	delete(additionalFields, "_created_at")
	delete(additionalFields, "_id")
	delete(additionalFields, "_org")
	delete(additionalFields, "_schema")
	delete(additionalFields, "_tags")
	delete(additionalFields, "_title")
	delete(additionalFields, "_updated_at")

	c.Entity = additionalFields

	return nil
}

func (c RelationAttributeActionsNewEntityItem) MarshalJSON() ([]byte, error) {
	out := map[string]interface{}{}
	bs, err := json.Marshal(_RelationAttributeActionsNewEntityItem(c))
	if err != nil {
		return nil, err
	}

	if err := json.Unmarshal([]byte(bs), &out); err != nil {
		return nil, err
	}

	bs, err = json.Marshal(c.Entity)
	if err != nil {
		return nil, err
	}

	if err := json.Unmarshal([]byte(bs), &out); err != nil {
		return nil, err
	}

	return json.Marshal(out)
}

type RelationAttributeActions struct {
	// The action type. Currently supported actions:
	//
	// | action | description |
	// |--------|-------------|
	// | add_existing | Enables the user to pick an existing entity to link as relation |
	// | create_new | Enables the user to create a new entity using the first/main `allowed_schemas` schema
	// | create_from_existing | Enables the user to pick an existing entity to clone from, while creating a blank new entity to link as relation |
	//
	ActionType *RelationAttributeActionsActionType `json:"action_type,omitempty"`
	// Sets the action as the default action, visible as the main action button.
	Default *bool `json:"default,omitempty"`
	// Name of the feature flag that enables this action
	FeatureFlag *string `json:"feature_flag,omitempty"`
	// The action label or action translation key (i18n)
	Label         *string                                `json:"label,omitempty"`
	NewEntityItem *RelationAttributeActionsNewEntityItem `json:"new_entity_item,omitempty"`
	// Name of the setting flag that enables this action
	SettingFlag *string `json:"setting_flag,omitempty"`
}

// RelationAttributeConstraints - A set of constraints applicable to the attribute.
// These constraints should and will be enforced by the attribute renderer.
type RelationAttributeConstraints struct {
}

type RelationAttributeDrawerSize string

const (
	RelationAttributeDrawerSizeSmall  RelationAttributeDrawerSize = "small"
	RelationAttributeDrawerSizeMedium RelationAttributeDrawerSize = "medium"
	RelationAttributeDrawerSizeLarge  RelationAttributeDrawerSize = "large"
)

func (e RelationAttributeDrawerSize) ToPointer() *RelationAttributeDrawerSize {
	return &e
}

func (e *RelationAttributeDrawerSize) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "small":
		fallthrough
	case "medium":
		fallthrough
	case "large":
		*e = RelationAttributeDrawerSize(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RelationAttributeDrawerSize: %v", v)
	}
}

type RelationAttributeEditMode string

const (
	RelationAttributeEditModeListView RelationAttributeEditMode = "list-view"
)

func (e RelationAttributeEditMode) ToPointer() *RelationAttributeEditMode {
	return &e
}

func (e *RelationAttributeEditMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list-view":
		*e = RelationAttributeEditMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RelationAttributeEditMode: %v", v)
	}
}

// RelationAttributeRelationAffinityMode - Weak relation attributes are kept when duplicating an entity. Strong relation attributes are discarded when duplicating an entity.
type RelationAttributeRelationAffinityMode string

const (
	RelationAttributeRelationAffinityModeWeak   RelationAttributeRelationAffinityMode = "weak"
	RelationAttributeRelationAffinityModeStrong RelationAttributeRelationAffinityMode = "strong"
)

func (e RelationAttributeRelationAffinityMode) ToPointer() *RelationAttributeRelationAffinityMode {
	return &e
}

func (e *RelationAttributeRelationAffinityMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "weak":
		fallthrough
	case "strong":
		*e = RelationAttributeRelationAffinityMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RelationAttributeRelationAffinityMode: %v", v)
	}
}

type RelationAttributeRelationType string

const (
	RelationAttributeRelationTypeHasMany RelationAttributeRelationType = "has_many"
	RelationAttributeRelationTypeHasOne  RelationAttributeRelationType = "has_one"
)

func (e RelationAttributeRelationType) ToPointer() *RelationAttributeRelationType {
	return &e
}

func (e *RelationAttributeRelationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "has_many":
		fallthrough
	case "has_one":
		*e = RelationAttributeRelationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RelationAttributeRelationType: %v", v)
	}
}

type RelationAttributeSummaryFieldsType string

const (
	RelationAttributeSummaryFieldsTypeStr          RelationAttributeSummaryFieldsType = "str"
	RelationAttributeSummaryFieldsTypeSummaryField RelationAttributeSummaryFieldsType = "SummaryField"
)

type RelationAttributeSummaryFields struct {
	Str          *string
	SummaryField *SummaryField

	Type RelationAttributeSummaryFieldsType
}

func CreateRelationAttributeSummaryFieldsStr(str string) RelationAttributeSummaryFields {
	typ := RelationAttributeSummaryFieldsTypeStr

	return RelationAttributeSummaryFields{
		Str:  &str,
		Type: typ,
	}
}

func CreateRelationAttributeSummaryFieldsSummaryField(summaryField SummaryField) RelationAttributeSummaryFields {
	typ := RelationAttributeSummaryFieldsTypeSummaryField

	return RelationAttributeSummaryFields{
		SummaryField: &summaryField,
		Type:         typ,
	}
}

func (u *RelationAttributeSummaryFields) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	str := new(string)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&str); err == nil {
		u.Str = str
		u.Type = RelationAttributeSummaryFieldsTypeStr
		return nil
	}

	summaryField := new(SummaryField)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&summaryField); err == nil {
		u.SummaryField = summaryField
		u.Type = RelationAttributeSummaryFieldsTypeSummaryField
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u RelationAttributeSummaryFields) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return json.Marshal(u.Str)
	}

	if u.SummaryField != nil {
		return json.Marshal(u.SummaryField)
	}

	return nil, nil
}

type RelationAttributeType string

const (
	RelationAttributeTypeRelation RelationAttributeType = "relation"
)

func (e RelationAttributeType) ToPointer() *RelationAttributeType {
	return &e
}

func (e *RelationAttributeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "relation":
		*e = RelationAttributeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RelationAttributeType: %v", v)
	}
}

// RelationAttribute - Entity Relationship
type RelationAttribute struct {
	Purpose []string                   `json:"_purpose,omitempty"`
	Actions []RelationAttributeActions `json:"actions,omitempty"`
	// Optional label for the add button. The translated value for add_button_lable is used, if found else the string is used as is.
	AddButtonLabel *string  `json:"add_button_label,omitempty"`
	AllowedSchemas []string `json:"allowedSchemas,omitempty"`
	// A set of constraints applicable to the attribute.
	// These constraints should and will be enforced by the attribute renderer.
	//
	Constraints  *RelationAttributeConstraints `json:"constraints,omitempty"`
	DefaultValue interface{}                   `json:"default_value,omitempty"`
	Deprecated   *bool                         `json:"deprecated,omitempty"`
	// Enables the preview, edition, and creation of relation items on a Master-Details view mode.
	DetailsViewModeEnabled *bool                        `json:"details_view_mode_enabled,omitempty"`
	DrawerSize             *RelationAttributeDrawerSize `json:"drawer_size,omitempty"`
	EditMode               *RelationAttributeEditMode   `json:"edit_mode,omitempty"`
	// When enable_relation_picker is set to true the user will be able to pick existing relations as values. Otherwise, the user will need to create new relation to link.
	EnableRelationPicker *bool `json:"enable_relation_picker,omitempty"`
	// When enable_relation_tags is set to true the user will be able to set tags(labels) in each relation item.
	EnableRelationTags *bool `json:"enable_relation_tags,omitempty"`
	// Setting to `true` disables editing the attribute on the entity builder UI
	EntityBuilderDisableEdit *bool `json:"entity_builder_disable_edit,omitempty"`
	// This attribute should only be active when the feature flag is enabled
	FeatureFlag *string `json:"feature_flag,omitempty"`
	// Which group the attribute should appear in. Accepts group ID or group name
	Group      *string `json:"group,omitempty"`
	HasPrimary *bool   `json:"has_primary,omitempty"`
	// Do not render attribute in entity views
	Hidden *bool `json:"hidden,omitempty"`
	// When set to true, will hide the label of the field.
	HideLabel *bool   `json:"hide_label,omitempty"`
	Icon      *string `json:"icon,omitempty"`
	Label     string  `json:"label"`
	Layout    *string `json:"layout,omitempty"`
	Name      string  `json:"name"`
	// Attribute sort order (ascending) in group
	Order                 *int64  `json:"order,omitempty"`
	Placeholder           *string `json:"placeholder,omitempty"`
	PreviewValueFormatter *string `json:"preview_value_formatter,omitempty"`
	// Setting to `true` prevents the attribute from being modified / deleted
	Protected *bool `json:"protected,omitempty"`
	Readonly  *bool `json:"readonly,omitempty"`
	// Weak relation attributes are kept when duplicating an entity. Strong relation attributes are discarded when duplicating an entity.
	RelationAffinityMode *RelationAttributeRelationAffinityMode `json:"relation_affinity_mode,omitempty"`
	RelationType         *RelationAttributeRelationType         `json:"relation_type,omitempty"`
	// Defines the conditional rendering expression for showing this field.
	// When a valid expression is parsed, their evaluation defines the visibility of this attribute.
	// Note: Empty or invalid expression have no effect on the field visibility.
	//
	RenderCondition *string `json:"render_condition,omitempty"`
	Required        *bool   `json:"required,omitempty"`
	// Map of schema slug to target relation attribute
	ReverseAttributes map[string]string `json:"reverse_attributes,omitempty"`
	// Optional placeholder text for the relation search input. The translated value for search_placeholder is used, if found else the string is used as is.
	SearchPlaceholder *string `json:"search_placeholder,omitempty"`
	// This attribute should only be active when the setting is enabled
	SettingFlag *string `json:"setting_flag,omitempty"`
	// Render as a column in table views. When defined, overrides `hidden`
	ShowInTable    *bool                            `json:"show_in_table,omitempty"`
	SummaryFields  []RelationAttributeSummaryFields `json:"summary_fields,omitempty"`
	Type           *RelationAttributeType           `json:"type,omitempty"`
	ValueFormatter *string                          `json:"value_formatter,omitempty"`
}
