// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-entity/internal/sdk/pkg/utils"
)

// RepeatableAttributeConstraints - A set of constraints applicable to the attribute.
// These constraints should and will be enforced by the attribute renderer.
type RepeatableAttributeConstraints struct {
}

// RepeatableAttributeRelationAffinityMode - Weak repeatable attributes are kept when duplicating an entity. Strong repeatable attributes are discarded when duplicating an entity.
type RepeatableAttributeRelationAffinityMode string

const (
	RepeatableAttributeRelationAffinityModeWeak   RepeatableAttributeRelationAffinityMode = "weak"
	RepeatableAttributeRelationAffinityModeStrong RepeatableAttributeRelationAffinityMode = "strong"
)

func (e RepeatableAttributeRelationAffinityMode) ToPointer() *RepeatableAttributeRelationAffinityMode {
	return &e
}

func (e *RepeatableAttributeRelationAffinityMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "weak":
		fallthrough
	case "strong":
		*e = RepeatableAttributeRelationAffinityMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RepeatableAttributeRelationAffinityMode: %v", v)
	}
}

type RepeatableAttributeType string

const (
	RepeatableAttributeTypeString         RepeatableAttributeType = "string"
	RepeatableAttributeTypePhone          RepeatableAttributeType = "phone"
	RepeatableAttributeTypeEmail          RepeatableAttributeType = "email"
	RepeatableAttributeTypeAddress        RepeatableAttributeType = "address"
	RepeatableAttributeTypeRelation       RepeatableAttributeType = "relation"
	RepeatableAttributeTypePayment        RepeatableAttributeType = "payment"
	RepeatableAttributeTypePriceComponent RepeatableAttributeType = "price_component"
	RepeatableAttributeTypeDate           RepeatableAttributeType = "date"
)

func (e RepeatableAttributeType) ToPointer() *RepeatableAttributeType {
	return &e
}

func (e *RepeatableAttributeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "string":
		fallthrough
	case "phone":
		fallthrough
	case "email":
		fallthrough
	case "address":
		fallthrough
	case "relation":
		fallthrough
	case "payment":
		fallthrough
	case "price_component":
		fallthrough
	case "date":
		*e = RepeatableAttributeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RepeatableAttributeType: %v", v)
	}
}

// RepeatableAttribute - Repeatable (add N number of fields)
type RepeatableAttribute struct {
	Purpose []string `json:"_purpose,omitempty"`
	// A set of constraints applicable to the attribute.
	// These constraints should and will be enforced by the attribute renderer.
	//
	Constraints  *RepeatableAttributeConstraints `json:"constraints,omitempty"`
	DefaultValue interface{}                     `json:"default_value,omitempty"`
	Deprecated   *bool                           `default:"false" json:"deprecated"`
	// when enable_relation_picker is set to true the user will be able to pick existing relations as values. Otherwise, the user will need to create new relation to link.
	EnableRelationPicker *bool `default:"true" json:"enable_relation_picker"`
	// Setting to `true` disables editing the attribute on the entity builder UI
	EntityBuilderDisableEdit *bool `default:"false" json:"entity_builder_disable_edit"`
	// This attribute should only be active when the feature flag is enabled
	FeatureFlag *string `json:"feature_flag,omitempty"`
	// Which group the attribute should appear in. Accepts group ID or group name
	Group      *string `json:"group,omitempty"`
	HasPrimary *bool   `json:"has_primary,omitempty"`
	// Do not render attribute in entity views
	Hidden *bool `default:"false" json:"hidden"`
	// When set to true, will hide the label of the field.
	HideLabel *bool `json:"hide_label,omitempty"`
	// Code name of the icon to used to represent this attribute.
	// The value must be a valid @epilot/base-elements Icon name
	//
	Icon   *string `json:"icon,omitempty"`
	Label  string  `json:"label"`
	Layout *string `json:"layout,omitempty"`
	Name   string  `json:"name"`
	// Attribute sort order (ascending) in group
	Order                 *int64  `json:"order,omitempty"`
	Placeholder           *string `json:"placeholder,omitempty"`
	PreviewValueFormatter *string `json:"preview_value_formatter,omitempty"`
	// Setting to `true` prevents the attribute from being modified / deleted
	Protected *bool `default:"true" json:"protected"`
	Readonly  *bool `default:"false" json:"readonly"`
	// Weak repeatable attributes are kept when duplicating an entity. Strong repeatable attributes are discarded when duplicating an entity.
	RelationAffinityMode *RepeatableAttributeRelationAffinityMode `json:"relation_affinity_mode,omitempty"`
	// Defines the conditional rendering expression for showing this field.
	// When a valid expression is parsed, their evaluation defines the visibility of this attribute.
	// Note: Empty or invalid expression have no effect on the field visibility.
	//
	RenderCondition *string `json:"render_condition,omitempty"`
	Repeatable      *bool   `json:"repeatable,omitempty"`
	Required        *bool   `default:"false" json:"required"`
	// This attribute should only be active when the setting is enabled
	SettingFlag *string `json:"setting_flag,omitempty"`
	// Render as a column in table views. When defined, overrides `hidden`
	ShowInTable    *bool                    `json:"show_in_table,omitempty"`
	Type           *RepeatableAttributeType `json:"type,omitempty"`
	ValueFormatter *string                  `json:"value_formatter,omitempty"`
}

func (r RepeatableAttribute) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RepeatableAttribute) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *RepeatableAttribute) GetPurpose() []string {
	if o == nil {
		return nil
	}
	return o.Purpose
}

func (o *RepeatableAttribute) GetConstraints() *RepeatableAttributeConstraints {
	if o == nil {
		return nil
	}
	return o.Constraints
}

func (o *RepeatableAttribute) GetDefaultValue() interface{} {
	if o == nil {
		return nil
	}
	return o.DefaultValue
}

func (o *RepeatableAttribute) GetDeprecated() *bool {
	if o == nil {
		return nil
	}
	return o.Deprecated
}

func (o *RepeatableAttribute) GetEnableRelationPicker() *bool {
	if o == nil {
		return nil
	}
	return o.EnableRelationPicker
}

func (o *RepeatableAttribute) GetEntityBuilderDisableEdit() *bool {
	if o == nil {
		return nil
	}
	return o.EntityBuilderDisableEdit
}

func (o *RepeatableAttribute) GetFeatureFlag() *string {
	if o == nil {
		return nil
	}
	return o.FeatureFlag
}

func (o *RepeatableAttribute) GetGroup() *string {
	if o == nil {
		return nil
	}
	return o.Group
}

func (o *RepeatableAttribute) GetHasPrimary() *bool {
	if o == nil {
		return nil
	}
	return o.HasPrimary
}

func (o *RepeatableAttribute) GetHidden() *bool {
	if o == nil {
		return nil
	}
	return o.Hidden
}

func (o *RepeatableAttribute) GetHideLabel() *bool {
	if o == nil {
		return nil
	}
	return o.HideLabel
}

func (o *RepeatableAttribute) GetIcon() *string {
	if o == nil {
		return nil
	}
	return o.Icon
}

func (o *RepeatableAttribute) GetLabel() string {
	if o == nil {
		return ""
	}
	return o.Label
}

func (o *RepeatableAttribute) GetLayout() *string {
	if o == nil {
		return nil
	}
	return o.Layout
}

func (o *RepeatableAttribute) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *RepeatableAttribute) GetOrder() *int64 {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *RepeatableAttribute) GetPlaceholder() *string {
	if o == nil {
		return nil
	}
	return o.Placeholder
}

func (o *RepeatableAttribute) GetPreviewValueFormatter() *string {
	if o == nil {
		return nil
	}
	return o.PreviewValueFormatter
}

func (o *RepeatableAttribute) GetProtected() *bool {
	if o == nil {
		return nil
	}
	return o.Protected
}

func (o *RepeatableAttribute) GetReadonly() *bool {
	if o == nil {
		return nil
	}
	return o.Readonly
}

func (o *RepeatableAttribute) GetRelationAffinityMode() *RepeatableAttributeRelationAffinityMode {
	if o == nil {
		return nil
	}
	return o.RelationAffinityMode
}

func (o *RepeatableAttribute) GetRenderCondition() *string {
	if o == nil {
		return nil
	}
	return o.RenderCondition
}

func (o *RepeatableAttribute) GetRepeatable() *bool {
	if o == nil {
		return nil
	}
	return o.Repeatable
}

func (o *RepeatableAttribute) GetRequired() *bool {
	if o == nil {
		return nil
	}
	return o.Required
}

func (o *RepeatableAttribute) GetSettingFlag() *string {
	if o == nil {
		return nil
	}
	return o.SettingFlag
}

func (o *RepeatableAttribute) GetShowInTable() *bool {
	if o == nil {
		return nil
	}
	return o.ShowInTable
}

func (o *RepeatableAttribute) GetType() *RepeatableAttributeType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *RepeatableAttribute) GetValueFormatter() *string {
	if o == nil {
		return nil
	}
	return o.ValueFormatter
}
