// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SavedViewItemCreatedBy1 - A user that created the view
type SavedViewItemCreatedBy1 struct {
	UserID *string `json:"user_id,omitempty"`
}

// SavedViewItem - A saved entity view
type SavedViewItem struct {
	CreatedAt *string     `json:"created_at,omitempty"`
	CreatedBy interface{} `json:"created_by"`
	// Generated uuid for a saved view
	ID *string `json:"id,omitempty"`
	// User-friendly identifier for the saved view
	Name string `json:"name"`
	// Organisation ID a view belongs to
	Org *string `json:"org,omitempty"`
	// boolean property for if a view is shared with organisation
	Shared *bool `json:"shared,omitempty"`
	// list of schemas a view can belong to
	Slug      []string               `json:"slug"`
	UIConfig  map[string]interface{} `json:"ui_config"`
	UpdatedAt *string                `json:"updated_at,omitempty"`
}
