// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SavedViewCreatedBy1 - A user that created the view
type SavedViewCreatedBy1 struct {
	UserID *string `json:"user_id,omitempty"`
}

// SavedView - A saved entity view
type SavedView struct {
	CreatedBy interface{} `json:"created_by"`
	// User-friendly identifier for the saved view
	Name string `json:"name"`
	// Organisation ID a view belongs to
	Org *string `json:"org,omitempty"`
	// boolean property for if a view is shared with organisation
	Shared *bool `json:"shared,omitempty"`
	// list of schemas a view can belong to
	Slug     []string               `json:"slug"`
	UIConfig map[string]interface{} `json:"ui_config"`
}
