// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SchemeEpilotAuth struct {
	Authorization string `security:"name=Authorization"`
}

type SchemeEpilotOrg struct {
	APIKey string `security:"name=x-epilot-org-id"`
}

type Security struct {
	EpilotAuth *SchemeEpilotAuth `security:"scheme,type=http,subtype=bearer"`
	EpilotOrg  *SchemeEpilotOrg  `security:"scheme,type=apiKey,subtype=header"`
}
