// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SummaryField - Summary Fields are displayed inside list view as a resume of the relation entity.
type SummaryField struct {
	// An hint on how to display the summary field
	DisplayAs *string `json:"display_as,omitempty"`
	// The field from the entity attributes to display
	Field *string `json:"field,omitempty"`
}
