// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Taxonomy - Taxonomy
type Taxonomy struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// A human friendly name of a Taxonomy e.g. Purpose, Product Category, Folder, Tag
	Name string `json:"name"`
	// Plural name of a Taxonomy e.g. Purposes, Product Categories, Folders, Tags
	Plural *string `json:"plural,omitempty"`
	// URL-friendly name for taxonomy
	Slug      string     `json:"slug"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}
