// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-entity/internal/sdk/pkg/utils"
	"time"
)

type Taxonomy struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// A human friendly name of a Taxonomy e.g. Purpose, Product Category, Folder, Tag
	Name string `json:"name"`
	// Plural name of a Taxonomy e.g. Purposes, Product Categories, Folders, Tags
	Plural *string `json:"plural,omitempty"`
	// URL-friendly name for taxonomy
	Slug      string     `json:"slug"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

func (t Taxonomy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Taxonomy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Taxonomy) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *Taxonomy) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Taxonomy) GetPlural() *string {
	if o == nil {
		return nil
	}
	return o.Plural
}

func (o *Taxonomy) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *Taxonomy) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
