// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type TaxonomyClassification struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	ID        *string    `json:"id,omitempty"`
	Name      string     `json:"name"`
	Parents   []string   `json:"parents,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}
