// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"encoding/json"
	"epilot-entity/internal/sdk/pkg/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"
)

func (r *EntityResourceModel) ToSDKType() interface{} {
	// Not Used

	return nil

}

func (r *EntityResourceModel) RefreshFromSDKType(resp *shared.EntityItem) {
	r.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	r.ID = types.StringValue(resp.ID)
	r.Org = types.StringValue(resp.Org)
	r.Schema = types.StringValue(resp.Schema)
	r.Tags = nil
	for _, v := range resp.Tags {
		r.Tags = append(r.Tags, types.StringValue(v))
	}
	r.Title = types.StringValue(resp.Title)
	r.UpdatedAt = types.StringValue(resp.UpdatedAt.Format(time.RFC3339))
	r.AdditionalProperties = make(map[string]types.String)
	for key, value := range resp.AdditionalProperties {
		result, _ := json.Marshal(value)
		r.AdditionalProperties[key] = types.StringValue(string(result))
	}

}
