// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type TableView struct {
	EntityDefaultTable *EntityDefaultTable `tfsdk:"entity_default_table"`
	EntityViewDisabled *EntityViewDisabled `tfsdk:"entity_view_disabled"`
	RedirectEntityView *RedirectEntityView `tfsdk:"redirect_entity_view"`
}
