// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type EntitySchemaUIConfigListItem struct {
	SummaryAttributes []SummaryAttribute `tfsdk:"summary_attributes"`
}
