// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type MultiSelectAttribute2 struct {
	Title types.String `tfsdk:"title"`
	Value types.String `tfsdk:"value"`
}
