// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type SelectAttributeOptions struct {
	Str                          types.String                  `tfsdk:"str"`
	SelectAttributeOptionsOption *MultiSelectAttributeOptions2 `tfsdk:"select_attribute_options_option"`
}
