// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type Attribute struct {
	AddressRelationAttribute       *AddressRelationAttribute       `tfsdk:"address_relation_attribute"`
	AutomationAttribute            *AutomationAttribute            `tfsdk:"automation_attribute"`
	BooleanAttribute               *BooleanAttribute               `tfsdk:"boolean_attribute"`
	ComputedAttribute              *ComputedAttribute              `tfsdk:"computed_attribute"`
	ConsentAttribute               *ConsentAttribute               `tfsdk:"consent_attribute"`
	CountryAttribute               *CountryAttribute               `tfsdk:"country_attribute"`
	CurrencyAttribute              *CurrencyAttribute              `tfsdk:"currency_attribute"`
	DateAttribute                  *DateAttribute                  `tfsdk:"date_attribute"`
	FileAttribute                  *FileAttribute                  `tfsdk:"file_attribute"`
	InternalAttribute              *InternalAttribute              `tfsdk:"internal_attribute"`
	InternalUserAttribute          *InternalUserAttribute          `tfsdk:"internal_user_attribute"`
	InvitationEmailAttribute       *InvitationEmailAttribute       `tfsdk:"invitation_email_attribute"`
	LinkAttribute                  *LinkAttribute                  `tfsdk:"link_attribute"`
	MultiSelectAttribute           *MultiSelectAttribute           `tfsdk:"multi_select_attribute"`
	NumberAttribute                *NumberAttribute                `tfsdk:"number_attribute"`
	OrderedListAttribute           *OrderedListAttribute           `tfsdk:"ordered_list_attribute"`
	PartnerStatusAttribute         *PartnerStatusAttribute         `tfsdk:"partner_status_attribute"`
	PaymentMethodRelationAttribute *PaymentMethodRelationAttribute `tfsdk:"payment_method_relation_attribute"`
	PurposeAttribute               *PurposeAttribute               `tfsdk:"purpose_attribute"`
	RelationAttribute              *RelationAttribute              `tfsdk:"relation_attribute"`
	RepeatableAttribute            *RepeatableAttribute            `tfsdk:"repeatable_attribute"`
	SelectAttribute                *SelectAttribute                `tfsdk:"select_attribute"`
	SequenceAttribute              *SequenceAttribute              `tfsdk:"sequence_attribute"`
	StatusAttribute                *StatusAttribute                `tfsdk:"status_attribute"`
	TagsAttribute                  *TagsAttribute                  `tfsdk:"tags_attribute"`
	TextAttribute                  *TextAttribute                  `tfsdk:"text_attribute"`
	UserRelationAttribute          *UserRelationAttribute          `tfsdk:"user_relation_attribute"`
}
