// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type EntityCapabilityUIHooks struct {
	Component          types.String                               `tfsdk:"component"`
	Disabled           types.Bool                                 `tfsdk:"disabled"`
	GroupExpanded      types.Bool                                 `tfsdk:"group_expanded"`
	Header             types.Bool                                 `tfsdk:"header"`
	Hook               types.String                               `tfsdk:"hook"`
	Icon               types.String                               `tfsdk:"icon"`
	Import             types.String                               `tfsdk:"import"`
	Order              types.Int64                                `tfsdk:"order"`
	RenderCondition    types.String                               `tfsdk:"render_condition"`
	RequiredPermission *EntityCapabilityUIHooksRequiredPermission `tfsdk:"required_permission"`
	Route              types.String                               `tfsdk:"route"`
	Title              types.String                               `tfsdk:"title"`
}
