// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Options struct {
	Str types.String           `tfsdk:"str"`
	Two *MultiSelectAttribute2 `tfsdk:"two"`
}
