// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type RedirectEntityView struct {
	Route    types.String `tfsdk:"route"`
	ViewType types.String `tfsdk:"view_type"`
}
