// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type InfoTooltipTitle struct {
	Default types.String `tfsdk:"default"`
	Key     types.String `tfsdk:"key"`
}
