// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type EntityDefaultCreate struct {
	SearchParams     map[string]types.String `tfsdk:"search_params"`
	TableMenuOptions *TableMenuOptions       `tfsdk:"table_menu_options"`
	ViewType         types.String            `tfsdk:"view_type"`
}
