// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type MultiSelectAttributeOptions struct {
	Str                          types.String                  `tfsdk:"str"`
	MultiSelectAttributeOptions2 *SelectAttributeOptionsOption `tfsdk:"multi_select_attribute_options_2"`
}
