// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type RelationAttributeActionsNewEntityItem struct {
	CreatedAt types.String            `tfsdk:"created_at"`
	ID        types.String            `tfsdk:"id"`
	Org       types.String            `tfsdk:"org"`
	Schema    types.String            `tfsdk:"schema"`
	Tags      []types.String          `tfsdk:"tags"`
	Title     types.String            `tfsdk:"title"`
	UpdatedAt types.String            `tfsdk:"updated_at"`
	Entity    map[string]types.String `tfsdk:"entity"`
}
