// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type NavbarActions struct {
	Options []EntityDefaultTableOptions `tfsdk:"options"`
	Type    types.String                `tfsdk:"type"`
}
