// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type CreateView struct {
	EntityDefaultCreate *EntityDefaultCreate `tfsdk:"entity_default_create"`
	EntityViewDisabled  *EntityViewDisabled  `tfsdk:"entity_view_disabled"`
	RedirectEntityView  *RedirectEntityView  `tfsdk:"redirect_entity_view"`
}
