// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type RelationAttributeActions2 struct {
	ActionType    types.String                            `tfsdk:"action_type"`
	Default       types.Bool                              `tfsdk:"default"`
	FeatureFlag   types.String                            `tfsdk:"feature_flag"`
	Label         types.String                            `tfsdk:"label"`
	NewEntityItem *RelationAttributeActionsNewEntityItem2 `tfsdk:"new_entity_item"`
	SettingFlag   types.String                            `tfsdk:"setting_flag"`
}
