// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type DropdownItems struct {
	One *EntityDefaultTable1 `tfsdk:"one"`
	Two *Two                 `tfsdk:"two"`
}
