// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type SummaryField struct {
	DisplayAs types.String `tfsdk:"display_as"`
	Field     types.String `tfsdk:"field"`
}
