// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type StatusAttributeOptions struct {
	Str                     types.String                  `tfsdk:"str"`
	StatusAttributeOptions2 *SelectAttributeOptionsOption `tfsdk:"status_attribute_options_2"`
}
