// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type CurrencyAttributeCurrency struct {
	CurrencyAttributeCurrency1 *CurrencyAttributeCurrency1 `tfsdk:"currency_attribute_currency_1"`
}
