// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Sharing struct {
	ShowSharingButton types.Bool `tfsdk:"show_sharing_button"`
}
