// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type RequiredPermission struct {
	Action   types.String `tfsdk:"action"`
	Resource types.String `tfsdk:"resource"`
}
