// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotentity/internal/sdk/pkg/models/shared"
	"net/http"
)

type AddRelationsRequest struct {
	RequestBody []shared.RelationItem `request:"mediaType=application/json"`
	// Don't wait for updated entity to become available in Search API. Useful for large migrations
	Async *bool `queryParam:"style=form,explode=true,name=async"`
	// Entity id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

type AddRelationsResponse struct {
	ContentType string
	// Success
	RelationItem *shared.RelationItem
	StatusCode   int
	RawResponse  *http.Response
}
