// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotentity/internal/sdk/pkg/models/shared"
	"net/http"
)

type AttachActivityPathParams struct {
	// Activity Id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type AttachActivityQueryParams struct {
	// Comma-separated list of entities which the activity primarily concerns
	Entities []string `queryParam:"style=form,explode=false,name=entities"`
}

type AttachActivityRequest struct {
	PathParams  AttachActivityPathParams
	QueryParams AttachActivityQueryParams
}

type AttachActivityResponse struct {
	// Success
	ActivityItem *shared.ActivityItem
	ContentType  string
	StatusCode   int
	RawResponse  *http.Response
}
