// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AutocompleteQueryParams struct {
	// Autocomplete attribute
	Attribute string `queryParam:"style=form,explode=true,name=attribute"`
	// Input to autocomplete
	Input *string `queryParam:"style=form,explode=true,name=input"`
	// Maximum number of results to return
	Size *int64 `queryParam:"style=form,explode=true,name=size"`
	// Limit results to entity schema
	Slug *string `queryParam:"style=form,explode=true,name=slug"`
}

type AutocompleteRequest struct {
	QueryParams AutocompleteQueryParams
}

// Autocomplete200ApplicationJSON - Success
type Autocomplete200ApplicationJSON struct {
	Hits    *float64      `json:"hits,omitempty"`
	Results []interface{} `json:"results,omitempty"`
}

type AutocompleteResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Success
	Autocomplete200ApplicationJSONObject *Autocomplete200ApplicationJSON
}
