// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilot-entity/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateActivityRequest struct {
	Activity *shared.Activity `request:"mediaType=application/json"`
	// Comma-separated list of entities which the activity primarily concerns
	Entities []string `queryParam:"style=form,explode=false,name=entities"`
}

type CreateActivityResponse struct {
	// Success
	ActivityItem *shared.ActivityItem
	ContentType  string
	StatusCode   int
	RawResponse  *http.Response
}
