// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteRelationPathParams struct {
	// The attribute that express meaning
	Attribute string `pathParam:"style=simple,explode=false,name=attribute"`
	// The attribute that express meaning
	EntityID string `pathParam:"style=simple,explode=false,name=entity_id"`
	// Entity id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

type DeleteRelationQueryParams struct {
	// Don't wait for updated entity to become available in Search API. Useful for large migrations
	Async *bool `queryParam:"style=form,explode=true,name=async"`
}

type DeleteRelationRequest struct {
	PathParams  DeleteRelationPathParams
	QueryParams DeleteRelationQueryParams
}

type DeleteRelationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
