// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteSavedViewRequest struct {
	// View id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type DeleteSavedViewResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
