// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotentity/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetActivityRequest struct {
	// Activity Id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Pagination offset for operations
	//
	OperationsFrom *int64 `queryParam:"style=form,explode=true,name=operations_from"`
	// Maximum number of operations to include in response (default: 10)
	//
	OperationsSize *int64 `queryParam:"style=form,explode=true,name=operations_size"`
}

type GetActivityResponse struct {
	// Success
	ActivityItem *shared.ActivityItem
	ContentType  string
	StatusCode   int
	RawResponse  *http.Response
}
