// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilot-entity/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetEntityRequest struct {
	// When true, enables entity hydration to resolve nested $relation & $relation_ref references in-place.
	Hydrate *bool `queryParam:"style=form,explode=true,name=hydrate"`
	// Entity id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

// GetEntity200ApplicationJSON - Success
type GetEntity200ApplicationJSON struct {
	Entity    *shared.EntityItem  `json:"entity,omitempty"`
	Relations []shared.EntityItem `json:"relations,omitempty"`
}

type GetEntityResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Success
	GetEntity200ApplicationJSONObject *GetEntity200ApplicationJSON
}
