// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilot-entity/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetSavedViewRequest struct {
	// View id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

// GetSavedView200ApplicationJSON - Success
type GetSavedView200ApplicationJSON struct {
	View *shared.SavedViewItem `json:"view,omitempty"`
}

type GetSavedViewResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Success
	GetSavedView200ApplicationJSONObject *GetSavedView200ApplicationJSON
}
