// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotentity/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetSchemaPathParams struct {
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

type GetSchemaQueryParams struct {
	ID *string `queryParam:"style=form,explode=true,name=id"`
}

type GetSchemaRequest struct {
	PathParams  GetSchemaPathParams
	QueryParams GetSchemaQueryParams
}

type GetSchemaResponse struct {
	ContentType string
	// Success
	EntitySchemaItem *shared.EntitySchemaItem
	StatusCode       int
	RawResponse      *http.Response
}
