// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilot-entity/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetTaxonomyRequest struct {
	// Taxonomy slug to return taxonomy for
	TaxonomySlug string `pathParam:"style=simple,explode=false,name=taxonomySlug"`
}

type GetTaxonomyResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Taxonomy
	Taxonomy *shared.Taxonomy
}
