// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilot-entity/internal/sdk/pkg/models/shared"
	"net/http"
)

type ImportEntitiesRequest struct {
	EntityImportParams *shared.EntityImportParams `request:"mediaType=application/json"`
	// Import Job Id to get the result
	JobID *string `queryParam:"style=form,explode=true,name=job_id"`
}

type ImportEntitiesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
