// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotentity/internal/sdk/pkg/models/shared"
	"net/http"
)

type ListSchemasQueryParams struct {
	// Return unpublished draft schemas
	Unpublished *bool `queryParam:"style=form,explode=true,name=unpublished"`
}

type ListSchemasRequest struct {
	QueryParams ListSchemasQueryParams
}

// ListSchemas200ApplicationJSON - Success
type ListSchemas200ApplicationJSON struct {
	Results []shared.EntitySchemaItem `json:"results,omitempty"`
}

type ListSchemasResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Success
	ListSchemas200ApplicationJSONObject *ListSchemas200ApplicationJSON
}
