// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotentity/internal/sdk/pkg/models/shared"
	"net/http"
)

// ListSavedViews200ApplicationJSON - Success
type ListSavedViews200ApplicationJSON struct {
	Results []shared.SavedViewItem `json:"results,omitempty"`
}

type ListSavedViewsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Success
	ListSavedViews200ApplicationJSONObject *ListSavedViews200ApplicationJSON
}
