// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

// ListSchemaBlueprintsResponseBody - Success
type ListSchemaBlueprintsResponseBody struct {
	Results []interface{} `json:"results,omitempty"`
}

func (o *ListSchemaBlueprintsResponseBody) GetResults() []interface{} {
	if o == nil {
		return nil
	}
	return o.Results
}

type ListSchemaBlueprintsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *ListSchemaBlueprintsResponseBody
}

func (o *ListSchemaBlueprintsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListSchemaBlueprintsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListSchemaBlueprintsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListSchemaBlueprintsResponse) GetObject() *ListSchemaBlueprintsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
