// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotentity/internal/sdk/pkg/models/shared"
	"net/http"
)

type PutSchemaPathParams struct {
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

type PutSchemaQueryParams struct {
	Draft *bool `queryParam:"style=form,explode=true,name=draft"`
}

type PutSchemaRequest struct {
	PathParams  PutSchemaPathParams
	QueryParams PutSchemaQueryParams
	Request     *shared.EntitySchema `request:"mediaType=application/json"`
}

// PutSchema200ApplicationJSON - Success
type PutSchema200ApplicationJSON struct {
	Results *shared.EntitySchemaItem `json:"results,omitempty"`
}

type PutSchemaResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Success
	PutSchema200ApplicationJSONObject *PutSchema200ApplicationJSON
}
