// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotentity/internal/sdk/pkg/models/shared"
	"net/http"
)

type SearchEntitiesResponse struct {
	ContentType string
	// Success
	EntitySearchResults *shared.EntitySearchResults
	StatusCode          int
	RawResponse         *http.Response
	// Success
	SearchEntities200TextCsvString *string
}
