// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotentity/internal/sdk/pkg/models/shared"
	"net/http"
)

type TaxonomiesClassificationsSearchQueryParams struct {
	// Taxonomy slug
	TaxonomySlug string `queryParam:"style=form,explode=true,name=taxonomySlug"`
}

type TaxonomiesClassificationsSearchRequestBody struct {
	ClassificationIds []string `json:"classificationIds,omitempty"`
}

type TaxonomiesClassificationsSearchRequest struct {
	QueryParams TaxonomiesClassificationsSearchQueryParams
	Request     *TaxonomiesClassificationsSearchRequestBody `request:"mediaType=application/json"`
}

// TaxonomiesClassificationsSearch200ApplicationJSON - Returns list of taxonomy classifications
type TaxonomiesClassificationsSearch200ApplicationJSON struct {
	Results []shared.TaxonomyClassification `json:"results,omitempty"`
}

type TaxonomiesClassificationsSearchResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns list of taxonomy classifications
	TaxonomiesClassificationsSearch200ApplicationJSONObject *TaxonomiesClassificationsSearch200ApplicationJSON
}
