// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilot-entity/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateClassificationsForTaxonomyRequest struct {
	ClassificationsUpdate *shared.ClassificationsUpdate `request:"mediaType=application/json"`
	// Taxonomy slug
	TaxonomySlug string `pathParam:"style=simple,explode=false,name=taxonomySlug"`
}

// UpdateClassificationsForTaxonomy200ApplicationJSON - Taxonomies classifications
type UpdateClassificationsForTaxonomy200ApplicationJSON struct {
	Created []shared.TaxonomyClassification `json:"created,omitempty"`
	Deleted map[string]interface{}          `json:"deleted,omitempty"`
	Updated []shared.TaxonomyClassification `json:"updated,omitempty"`
}

type UpdateClassificationsForTaxonomyResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Taxonomies classifications
	UpdateClassificationsForTaxonomy200ApplicationJSONObject *UpdateClassificationsForTaxonomy200ApplicationJSON
}
