// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotentity/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateSavedViewPathParams struct {
	// View id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type UpdateSavedViewRequest struct {
	PathParams UpdateSavedViewPathParams
	Request    *shared.SavedView `request:"mediaType=application/json"`
}

type UpdateSavedViewResponse struct {
	ContentType string
	// Success
	SavedViewItem *shared.SavedViewItem
	StatusCode    int
	RawResponse   *http.Response
}
