// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-entity/internal/sdk/pkg/models/shared"
	"github.com/epilot-dev/terraform-provider-epilot-entity/internal/sdk/pkg/utils"
	"net/http"
)

type UpsertEntityRequestBody struct {
	Entity    shared.Entity `json:"entity"`
	UniqueKey []string      `json:"unique_key"`
}

func (o *UpsertEntityRequestBody) GetEntity() shared.Entity {
	if o == nil {
		return shared.Entity{}
	}
	return o.Entity
}

func (o *UpsertEntityRequestBody) GetUniqueKey() []string {
	if o == nil {
		return []string{}
	}
	return o.UniqueKey
}

type UpsertEntityRequest struct {
	RequestBody *UpsertEntityRequestBody `request:"mediaType=application/json"`
	// Activity to include in event feed
	ActivityID *string `queryParam:"style=form,explode=true,name=activity_id"`
	// Don't wait for updated entity to become available in Search API. Useful for large migrations
	Async *bool `default:"false" queryParam:"style=form,explode=true,name=async"`
	// Dry Run mode = return matched entities but don't update them.
	DryRun *bool `default:"false" queryParam:"style=form,explode=true,name=dry_run"`
	// Entity Schema
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (u UpsertEntityRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpsertEntityRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UpsertEntityRequest) GetRequestBody() *UpsertEntityRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *UpsertEntityRequest) GetActivityID() *string {
	if o == nil {
		return nil
	}
	return o.ActivityID
}

func (o *UpsertEntityRequest) GetAsync() *bool {
	if o == nil {
		return nil
	}
	return o.Async
}

func (o *UpsertEntityRequest) GetDryRun() *bool {
	if o == nil {
		return nil
	}
	return o.DryRun
}

func (o *UpsertEntityRequest) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

type UpsertEntityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Entity was updated
	EntityItem *shared.EntityItem
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpsertEntityResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpsertEntityResponse) GetEntityItem() *shared.EntityItem {
	if o == nil {
		return nil
	}
	return o.EntityItem
}

func (o *UpsertEntityResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpsertEntityResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
