// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilot-entity/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpsertEntityRequestBody struct {
	Entity    shared.Entity `json:"entity"`
	UniqueKey []string      `json:"unique_key"`
}

type UpsertEntityRequest struct {
	RequestBody *UpsertEntityRequestBody `request:"mediaType=application/json"`
	// Activity to include in event feed
	ActivityID *string `queryParam:"style=form,explode=true,name=activity_id"`
	// Don't wait for updated entity to become available in Search API. Useful for large migrations
	Async *bool `queryParam:"style=form,explode=true,name=async"`
	// Dry Run mode = return matched entities but don't update them.
	DryRun *bool `queryParam:"style=form,explode=true,name=dry_run"`
	// Entity Schema
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

type UpsertEntityResponse struct {
	ContentType string
	// Entity was updated
	EntityItem  *shared.EntityItem
	StatusCode  int
	RawResponse *http.Response
}
